// Generated by CoffeeScript 1.9.3
(function() {
  var lotus;

  lotus = require("lotus-require");

  if (lotus == null) {
    lotus = {};
  }

  lotus.log = require("lotus-log");

  module.exports = lotus;

  Object.defineProperty(global, "_lotus_", {
    get: function() {
      return lotus;
    }
  });

}).call(this);
