// Generated by CoffeeScript 1.10.0
(function() {
  var Path, color, exit, gaze, ln, log, lotus, ref, semver, sync;

  lotus = require("lotus-require");

  ref = require("lotus-log"), log = ref.log, ln = ref.ln, color = ref.color;

  sync = require("io").sync;

  semver = require("semver");

  Path = require("path");

  gaze = require("gaze");

  exit = require("exit");

  module.exports = function(options) {
    var fromJSON, isCached, promise, ref1, startTime, toJSON;
    ref1 = require("./persistence"), toJSON = ref1.toJSON, fromJSON = ref1.fromJSON;
    isCached = sync.isFile("lotus-cache.json");
    startTime = Date.now();
    if (isCached) {
      promise = fromJSON();
    } else {
      log.moat(1).white("Crawling: ").yellow(lotus.path).moat(1);
      promise = Module.initialize();
    }
    return promise.then(function() {
      var isDirty;
      log.moat(1).yellow(Object.keys(Module.cache).length).white(" modules were found").gray(" (in " + (Date.now() - startTime) + " ms)").moat(1);
      if (!isCached) {
        toJSON().done();
      }
      isDirty = false;
      Module._emitter.on("file event", function() {
        return isDirty = true;
      });
      return exit.on(function() {
        if (isDirty) {
          return toJSON().done();
        }
      });
    }).done();
  };

}).call(this);
