// Generated by CoffeeScript 1.12.7
module.exports = function() {
  var command, minimist, options;
  require("./global");
  require("./index");
  process.exit = (function() {
    var exit;
    exit = process.exit.bind(process);
    return function() {
      log.moat(1);
      return log.onceFlushed(exit);
    };
  })();
  log.indent = 2;
  log.moat(1);
  minimist = require("minimist");
  options = minimist(process.argv.slice(2));
  command = options._.join(" ");
  delete options._;
  return lotus.run(command, options).fail(function(error) {
    return console.log(error.stack);
  }).then(process.exit);
};
